// Generated by gencpp from file vehicle_controller/CalibrationResponse.msg
// DO NOT EDIT!


#ifndef VEHICLE_CONTROLLER_MESSAGE_CALIBRATIONRESPONSE_H
#define VEHICLE_CONTROLLER_MESSAGE_CALIBRATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vehicle_controller
{
template <class ContainerAllocator>
struct CalibrationResponse_
{
  typedef CalibrationResponse_<ContainerAllocator> Type;

  CalibrationResponse_()
    : success(false)  {
    }
  CalibrationResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::vehicle_controller::CalibrationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_controller::CalibrationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CalibrationResponse_

typedef ::vehicle_controller::CalibrationResponse_<std::allocator<void> > CalibrationResponse;

typedef boost::shared_ptr< ::vehicle_controller::CalibrationResponse > CalibrationResponsePtr;
typedef boost::shared_ptr< ::vehicle_controller::CalibrationResponse const> CalibrationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_controller::CalibrationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_controller::CalibrationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vehicle_controller::CalibrationResponse_<ContainerAllocator1> & lhs, const ::vehicle_controller::CalibrationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vehicle_controller::CalibrationResponse_<ContainerAllocator1> & lhs, const ::vehicle_controller::CalibrationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vehicle_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vehicle_controller::CalibrationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_controller::CalibrationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_controller::CalibrationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_controller::CalibrationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_controller::CalibrationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_controller::CalibrationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_controller::CalibrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::vehicle_controller::CalibrationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_controller::CalibrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_controller/CalibrationResponse";
  }

  static const char* value(const ::vehicle_controller::CalibrationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_controller::CalibrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool success\n"
;
  }

  static const char* value(const ::vehicle_controller::CalibrationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_controller::CalibrationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalibrationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_controller::CalibrationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_controller::CalibrationResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_CONTROLLER_MESSAGE_CALIBRATIONRESPONSE_H
