// Generated by gencpp from file maxon_epos2/MotorStates.msg
// DO NOT EDIT!


#ifndef MAXON_EPOS2_MESSAGE_MOTORSTATES_H
#define MAXON_EPOS2_MESSAGE_MOTORSTATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <maxon_epos2/MotorState.h>

namespace maxon_epos2
{
template <class ContainerAllocator>
struct MotorStates_
{
  typedef MotorStates_<ContainerAllocator> Type;

  MotorStates_()
    : motor_states()  {
    }
  MotorStates_(const ContainerAllocator& _alloc)
    : motor_states(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::maxon_epos2::MotorState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::maxon_epos2::MotorState_<ContainerAllocator> >::other >  _motor_states_type;
  _motor_states_type motor_states;





  typedef boost::shared_ptr< ::maxon_epos2::MotorStates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maxon_epos2::MotorStates_<ContainerAllocator> const> ConstPtr;

}; // struct MotorStates_

typedef ::maxon_epos2::MotorStates_<std::allocator<void> > MotorStates;

typedef boost::shared_ptr< ::maxon_epos2::MotorStates > MotorStatesPtr;
typedef boost::shared_ptr< ::maxon_epos2::MotorStates const> MotorStatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maxon_epos2::MotorStates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maxon_epos2::MotorStates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maxon_epos2::MotorStates_<ContainerAllocator1> & lhs, const ::maxon_epos2::MotorStates_<ContainerAllocator2> & rhs)
{
  return lhs.motor_states == rhs.motor_states;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maxon_epos2::MotorStates_<ContainerAllocator1> & lhs, const ::maxon_epos2::MotorStates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maxon_epos2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maxon_epos2::MotorStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maxon_epos2::MotorStates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maxon_epos2::MotorStates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maxon_epos2::MotorStates_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maxon_epos2::MotorStates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maxon_epos2::MotorStates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maxon_epos2::MotorStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5b0a65f417d44d6769d684f20442892";
  }

  static const char* value(const ::maxon_epos2::MotorStates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5b0a65f417d44d6ULL;
  static const uint64_t static_value2 = 0x769d684f20442892ULL;
};

template<class ContainerAllocator>
struct DataType< ::maxon_epos2::MotorStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maxon_epos2/MotorStates";
  }

  static const char* value(const ::maxon_epos2::MotorStates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maxon_epos2::MotorStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MotorState[] motor_states\n"
"================================================================================\n"
"MSG: maxon_epos2/MotorState\n"
"int32   motor_id\n"
"float64 pos\n"
"float64 vel\n"
"float64 cur\n"
;
  }

  static const char* value(const ::maxon_epos2::MotorStates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maxon_epos2::MotorStates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor_states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorStates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maxon_epos2::MotorStates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maxon_epos2::MotorStates_<ContainerAllocator>& v)
  {
    s << indent << "motor_states[]" << std::endl;
    for (size_t i = 0; i < v.motor_states.size(); ++i)
    {
      s << indent << "  motor_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::maxon_epos2::MotorState_<ContainerAllocator> >::stream(s, indent + "    ", v.motor_states[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAXON_EPOS2_MESSAGE_MOTORSTATES_H
